### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by jeremieroy** [bkconrad/screeps-grafana#2]
Hi sorry to bother you,
I have a couple of questions/remarks:
a) In the ansible command you are supposed to give information about your private key:
--private-key YOURPRIVATEKEY \
And I'm unsure how to handle that :
Are you referring to the aws private key ?
Is it a filename, then are we supposed to upload our private key to our server ?
If that is the case, what will it be used for ?

So far, I didn't upload my private, and used the name of my aws key pair as command argument.
No idea if it did anything or not, but my grafana instance is working perfectly. So I'm unsure what I am missing.

b) to make the command work, I had to add "-c local" as extra arguments.

c) What is the poll rate of the metrics, do we have data for every tick ?
It looks like the polling is every 10s.

d) There a bit of a lack of documentations for the stats.js example,
there is a lot of variables that are used but not declared/computed.
I understand that we are supposed to figure it out ourselves and customize the board to our needs...
But as a starter it would make things easier to limit it to a set of working metrics.
I also understand that the appropriate answers from you to this remark should be: you're welcome to make PR proposal ;)

Anyway I'd like to thank you for sharing this project, it is greatly appreciated :)

**Comment by Triscus** [comment]
Hi jeremieroy,

yesterday I was able to install screep-graphana on an aws server, it took me two attempts :) 

The purpose of ansible is the installation of docker and the graphana stuff. From my understanding it is normally used for remote installation of software in larger enviroments, that's why you need the private key, because the server is connecting to itself. 

I uploaded the private key (pem-file) and replaced YOURPRIVATEKEY with the path to it and deleted it afterwards.

Regards

Triscus
